/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysticLaunch.ui.panels;

import com.mysticcore.util.CustomFileFilter;
import javax.swing.JFileChooser;

/**
 *
 * @author Pruzer
 */
public class pnlEdit extends javax.swing.JPanel {

    /**
     * Creates new form pnlEdit
     */
    public pnlEdit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnUpdateEntry = new javax.swing.JButton();
        btnCancelEntry = new javax.swing.JButton();
        txtStartIn = new javax.swing.JTextField();
        txtPath = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtParms = new javax.swing.JTextField();
        txtAltIcon = new javax.swing.JTextField();
        btnOFPath = new javax.swing.JButton();
        btnOFStartIn = new javax.swing.JButton();
        btnOFAltIcon = new javax.swing.JButton();

        setBackground(new java.awt.Color(83, 83, 128));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 170, 62));
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 170, 62));
        jLabel3.setText("Path:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 170, 62));
        jLabel4.setText("StartIn:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 170, 62));
        jLabel5.setText("Parms:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 170, 62));
        jLabel6.setText("Alt Icon:");

        btnUpdateEntry.setText("Update");
        btnUpdateEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateEntryActionPerformed(evt);
            }
        });

        btnCancelEntry.setText("Cancel");
        btnCancelEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelEntryActionPerformed(evt);
            }
        });

        btnOFPath.setText("?");
        btnOFPath.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnOFPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOFPathActionPerformed(evt);
            }
        });

        btnOFStartIn.setText("?");
        btnOFStartIn.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnOFStartIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOFStartInActionPerformed(evt);
            }
        });

        btnOFAltIcon.setText("?");
        btnOFAltIcon.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnOFAltIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOFAltIconActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdateEntry)
                .addGap(29, 29, 29)
                .addComponent(btnCancelEntry)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAltIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOFAltIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtParms, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtStartIn)
                                .addComponent(txtPath, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnOFStartIn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnOFPath, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(btnOFPath))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStartIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(btnOFStartIn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtParms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAltIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOFAltIcon))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelEntry)
                    .addComponent(btnUpdateEntry))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEntryActionPerformed
        pnlEdit.setVisible(false);
        pnlMain.setVisible(true);
    }//GEN-LAST:event_btnUpdateEntryActionPerformed

    private void btnCancelEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelEntryActionPerformed
        pnlEdit.setVisible(false);
        pnlMain.setVisible(true);
    }//GEN-LAST:event_btnCancelEntryActionPerformed

    private void btnOFPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOFPathActionPerformed
        JFileChooser fc = new JFileChooser();
        //fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setFileFilter(new CustomFileFilter("exe"));
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {  txtPath.setText(fc.getSelectedFile().toString());
        }
    }//GEN-LAST:event_btnOFPathActionPerformed

    private void btnOFStartInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOFStartInActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {  txtStartIn.setText(fc.getSelectedFile().toString());
        }
    }//GEN-LAST:event_btnOFStartInActionPerformed

    private void btnOFAltIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOFAltIconActionPerformed
        JFileChooser fc = new JFileChooser();
        //fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setFileFilter(new CustomFileFilter("ico"));
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {  txtAltIcon.setText(fc.getSelectedFile().toString());
        }
    }//GEN-LAST:event_btnOFAltIconActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelEntry;
    private javax.swing.JButton btnOFAltIcon;
    private javax.swing.JButton btnOFPath;
    private javax.swing.JButton btnOFStartIn;
    private javax.swing.JButton btnUpdateEntry;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAltIcon;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtParms;
    private javax.swing.JTextField txtPath;
    private javax.swing.JTextField txtStartIn;
    // End of variables declaration//GEN-END:variables
}
