/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mysticLaunch.ui;

import com.mysticcore.util.CustomFileFilter;
import javax.swing.JFileChooser;
import mysticLaunch.bean.AppInfoBean;
import mysticLaunch.util.DataHelper;

/**
 *
 * @author IM01DXP
 */
public class DlgConfig extends javax.swing.JDialog {
    
    DataHelper _dh = DataHelper.singleton();

    /**
     * Creates new form DlgConfig
     */
    public DlgConfig(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lstAliases.setListData(_dh.getAliasNames().toArray());
    }

    public void centerDialog(int offsetX, int offsetY) {
       java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
       int x = (screenSize.width - this.getWidth())/2 + offsetX;
       int y = (screenSize.height-this.getHeight())/2 + offsetY;
       System.out.println("Centering on [" + x + "," + y + "].");
       setLocation( x,y );
    }    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        pnlMain = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAliases = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstEntries = new javax.swing.JList();
        btnRemoveAlias = new javax.swing.JButton();
        btnAddAlias = new javax.swing.JButton();
        btnRemoveEntry = new javax.swing.JButton();
        btnAddEntry = new javax.swing.JButton();
        lblAliases = new javax.swing.JLabel();
        lblEntries = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlEdit = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnUpdateEntry = new javax.swing.JButton();
        btnCancelEntry = new javax.swing.JButton();
        txtStartIn = new javax.swing.JTextField();
        txtPath = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtParms = new javax.swing.JTextField();
        txtAltIcon = new javax.swing.JTextField();
        btnOFPath = new javax.swing.JButton();
        btnOFStartIn = new javax.swing.JButton();
        btnOFAltIcon = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(41, 55, 58));

        lstAliases.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstAliases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAliasesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstAliases);

        lstEntries.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstEntries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstEntriesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstEntries);

        btnRemoveAlias.setText("-");
        btnRemoveAlias.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnRemoveAlias.setMaximumSize(null);
        btnRemoveAlias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveAliasActionPerformed(evt);
            }
        });

        btnAddAlias.setText("+");
        btnAddAlias.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnAddAlias.setMaximumSize(null);
        btnAddAlias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAliasActionPerformed(evt);
            }
        });

        btnRemoveEntry.setText("-");
        btnRemoveEntry.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnRemoveEntry.setMaximumSize(null);
        btnRemoveEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveEntryActionPerformed(evt);
            }
        });

        btnAddEntry.setText("+");
        btnAddEntry.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnAddEntry.setMaximumSize(null);
        btnAddEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEntryActionPerformed(evt);
            }
        });

        lblAliases.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAliases.setForeground(new java.awt.Color(255, 170, 62));
        lblAliases.setText("Aliases:");

        lblEntries.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEntries.setForeground(new java.awt.Color(255, 170, 62));
        lblEntries.setText("Entries:");

        jLabel1.setForeground(new java.awt.Color(128, 192, 96));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("(Double Click to Edit)");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(lblAliases)
                                .addGap(92, 92, 92)
                                .addComponent(btnRemoveAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                                .addComponent(lblEntries)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRemoveEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlMainLayout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnRemoveAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAddAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRemoveEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAddEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblAliases)))
                    .addComponent(lblEntries, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnlEdit.setBackground(new java.awt.Color(41, 55, 58));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 170, 62));
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 170, 62));
        jLabel3.setText("Path:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 170, 62));
        jLabel4.setText("StartIn:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 170, 62));
        jLabel5.setText("Parms:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 170, 62));
        jLabel6.setText("Alt Icon:");

        btnUpdateEntry.setText("Update");
        btnUpdateEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateEntryActionPerformed(evt);
            }
        });

        btnCancelEntry.setText("Cancel");
        btnCancelEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelEntryActionPerformed(evt);
            }
        });

        btnOFPath.setText("?");
        btnOFPath.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnOFPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOFPathActionPerformed(evt);
            }
        });

        btnOFStartIn.setText("?");
        btnOFStartIn.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnOFStartIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOFStartInActionPerformed(evt);
            }
        });

        btnOFAltIcon.setText("?");
        btnOFAltIcon.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnOFAltIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOFAltIconActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditLayout = new javax.swing.GroupLayout(pnlEdit);
        pnlEdit.setLayout(pnlEditLayout);
        pnlEditLayout.setHorizontalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditLayout.createSequentialGroup()
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlEditLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdateEntry)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelEntry))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlEditLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlEditLayout.createSequentialGroup()
                                .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnOFPath, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEditLayout.createSequentialGroup()
                                .addComponent(txtStartIn, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnOFStartIn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtParms, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlEditLayout.createSequentialGroup()
                                .addComponent(txtAltIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnOFAltIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pnlEditLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtName, txtParms});

        pnlEditLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAltIcon, txtPath, txtStartIn});

        pnlEditLayout.setVerticalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlEditLayout.createSequentialGroup()
                        .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(btnOFPath))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStartIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(btnOFStartIn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtParms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAltIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOFAltIcon))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateEntry)
                    .addComponent(btnCancelEntry))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveAliasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAliasActionPerformed
        String val = (String) lstAliases.getSelectedValue();
        if (val != null)
        {  System.out.println("Selected for Removal: " + val);
           _dh.removeAlias(val);
        }
    }//GEN-LAST:event_btnRemoveAliasActionPerformed

    private void btnAddAliasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAliasActionPerformed
        System.out.println("Adding Alias..");
        _dh.addAlias(null);
    }//GEN-LAST:event_btnAddAliasActionPerformed

    private void btnRemoveEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveEntryActionPerformed
        String alias = (String) lstAliases.getSelectedValue();
        String val = (String) lstEntries.getSelectedValue();
        if (val != null)
        {  System.out.println("Selected for Removal: " + val);
           AppInfoBean aib = _dh.getBeanInfo(alias, val);
           _dh.removeEntry(alias, aib);
        }
    }//GEN-LAST:event_btnRemoveEntryActionPerformed

    private void btnAddEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEntryActionPerformed
        System.out.println("Adding Entry..");
        String alias = (String) lstAliases.getSelectedValue();
        AppInfoBean aib = new AppInfoBean();
        _dh.addEntry(alias, aib);
    }//GEN-LAST:event_btnAddEntryActionPerformed

    private void lstAliasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAliasesMouseClicked
        if (evt.getClickCount() == 1)
        {  lstEntries.setListData(_dh.getEntryNames((String) lstAliases.getSelectedValue()).toArray());
        }
        else if (evt.getClickCount() == 2) 
        {  System.out.println("Editing:" + (String) lstAliases.getSelectedValue());
           pnlMain.setVisible(false);
           pnlEdit.setVisible(true);        
        }
    }//GEN-LAST:event_lstAliasesMouseClicked

    private void lstEntriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEntriesMouseClicked
        if (evt.getClickCount() == 2) 
        {  System.out.println("Editing:" + (String) lstEntries.getSelectedValue());
           pnlMain.setVisible(false);
           pnlEdit.setVisible(true);
        }
    }//GEN-LAST:event_lstEntriesMouseClicked

    
    private void btnOFPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOFPathActionPerformed
         JFileChooser fc = new JFileChooser();
         //fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
         fc.setFileFilter(new CustomFileFilter("exe"));
         if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) 
         {  txtPath.setText(fc.getSelectedFile().toString());
         }
    }//GEN-LAST:event_btnOFPathActionPerformed

    
    private void btnOFStartInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOFStartInActionPerformed
         JFileChooser fc = new JFileChooser();
         fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
         if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) 
         {  txtStartIn.setText(fc.getSelectedFile().toString());
         }
    }//GEN-LAST:event_btnOFStartInActionPerformed

    
    private void btnOFAltIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOFAltIconActionPerformed
         JFileChooser fc = new JFileChooser();
         //fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
         fc.setFileFilter(new CustomFileFilter("ico"));
         if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) 
         {  txtAltIcon.setText(fc.getSelectedFile().toString());
         }
    }//GEN-LAST:event_btnOFAltIconActionPerformed

    private void btnUpdateEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEntryActionPerformed
        pnlEdit.setVisible(false);
        pnlMain.setVisible(true);
    }//GEN-LAST:event_btnUpdateEntryActionPerformed

    private void btnCancelEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelEntryActionPerformed
        pnlEdit.setVisible(false);
        pnlMain.setVisible(true);
    }//GEN-LAST:event_btnCancelEntryActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgConfig dialog = new DlgConfig(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAlias;
    private javax.swing.JButton btnAddEntry;
    private javax.swing.JButton btnCancelEntry;
    private javax.swing.JButton btnOFAltIcon;
    private javax.swing.JButton btnOFPath;
    private javax.swing.JButton btnOFStartIn;
    private javax.swing.JButton btnRemoveAlias;
    private javax.swing.JButton btnRemoveEntry;
    private javax.swing.JButton btnUpdateEntry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAliases;
    private javax.swing.JLabel lblEntries;
    private javax.swing.JList lstAliases;
    private javax.swing.JList lstEntries;
    private javax.swing.JPanel pnlEdit;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTextField txtAltIcon;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtParms;
    private javax.swing.JTextField txtPath;
    private javax.swing.JTextField txtStartIn;
    // End of variables declaration//GEN-END:variables
}
